name: deploy-tickets

on:
  push:
    branches:
      - master
    paths:
      - 'tickets/**'

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  REPOSITORY: 2up1down/tickets

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build docker image
        run: cd auth && docker build -t $REPOSITORY .

      - name: Log in to docker hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Push to docker hub
        run: docker push $REPOSITORY

